default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  database: resource_matching_development

test:
  <<: *default
  database: resource_matching_test

production:
  <<: *default