test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>



google:
  service: GCS
  project: buydeis
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: buydeis-bucket
google_dev:
  service: GCS
  project: buydeis
  credentials: <%= Rails.root.join("config/secrets/buydeis.json") %>
  bucket: buydeis-bucket
